name: PR

on:
  pull_request:
    branches:
      - main

concurrency:
  group: '${{ github.workflow }}-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  linting:
    name: Lint Testing
    runs-on: ubuntu-latest

    permissions:
      contents: read
      statuses: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Lint Testing
        uses: super-linter/super-linter@v8
        env:
          DEFAULT_BRANCH: 'main'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_JSON: true
          VALIDATE_MARKDOWN: true
          VALIDATE_POWERSHELL: true
          VALIDATE_YAML: true

  markdown-links:
    name: Validate Markdown Links
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Check Links in Markdown Files
        uses: gaurav-nelson/github-action-markdown-link-check@1.0.17
        with:
          config-file: '.github/linters/.markdown-link-check.json'
          check-modified-files-only: 'yes'
          use-verbose-mode: 'yes'
          use-quiet-mode: 'yes'
          base-branch: main
